---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/alerts

resources:
  - ./audiobookshelf/ks.yaml
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./dashbrr/ks.yaml
  - ./filebrowser/ks.yaml
  - ./immich/ks.yaml
  - ./kavita/ks.yaml
  - ./lidarr/ks.yaml
  - ./music-assistant/ks.yaml
  - ./notifiarr/ks.yaml
  - ./pinepods/ks.yaml
  - ./plex/ks.yaml
  - ./radarr/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
  - ./unpackerr/ks.yaml