[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"

_.file = [
  "{{config_root}}/.secrets.env",
]

[tools]
"uv" = "latest"
"pipx:flux-local" = "latest"
"python" = "3.14.3"
"pipx:makejinja" = "2.8.2"
"aqua:casey/just" = "latest"
"aqua:cert-manager/cmctl" = "latest"
"aqua:cilium/cilium-cli" = "0.19.1"
"aqua:cli/cli" = "2.86.0"
"aqua:cloudflare/cloudflared" = "2026.2.0"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:helm/helm" = "latest"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:kubernetes/kubernetes/kubectl" = "1.35.1"
"aqua:mikefarah/yq" = "4.52.3"
"aqua:siderolabs/talos" = "1.12.4"
"aqua:yannh/kubeconform" = "0.7.0"
"github:clbx/kubectl-browse-pvc" = "latest"
"github:charmbracelet/gum" = "v0.17.0"
"github:EnterpriseDB/kubectl-cnp" = "1.28.0"
"github:mitsuhiko/minijinja" = "2.13.0"
"github:rook/kubectl-rook-ceph" = "latest"