---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jonandlinz.io
spec:
  dnsNames:
    - jonandlinz.io
    - "*.jonandlinz.io"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: jonandlinz-io-tls
  usages:
    - digital signature