---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: convertx
spec:
  components:
    - ../../../../components/gpu
    - ../../../../components/gateway-oidc
    - ../../../../components/volsync
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/default/convertx/app
  postBuild:
    substitute:
      APP: convertx
      APP_SUBDOMAIN: fileconvert
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false