---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rmqtt
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rmqtt
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      rmqtt:
        type: statefulset
        strategy: RollingUpdate
        statefulset:
          startOrdinal: 1
          podManagementPolicy: OrderedReady
          serviceName: rmqtt
        replicas: 3
        containers:
          app:
            image:
              repository: docker.io/rmqtt/rmqtt
              tag: 0.18.0@sha256:cf9d547b472ad981d43c7eeaf4717abbbf2c0ab15428a56b21cb47e9ecb9e34c
            env:
              POD_ID:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
              TZ: America/Chicago
            args:
              - --id=$(POD_ID)
              - --plugins-default-startups
              - rmqtt-cluster-raft
              - rmqtt-retainer
              - --node-grpc-addrs
              - 1@rmqtt-1.rmqtt.database.svc.cluster.local:5363
              - 2@rmqtt-2.rmqtt.database.svc.cluster.local:5363
              - 3@rmqtt-3.rmqtt.database.svc.cluster.local:5363
              - --raft-peer-addrs
              - 1@rmqtt-1.rmqtt.database.svc.cluster.local:6003
              - 2@rmqtt-2.rmqtt.database.svc.cluster.local:6003
              - 3@rmqtt-3.rmqtt.database.svc.cluster.local:6003
            #probes:
            #  liveness: &probes
            #    enabled: true
            #    custom: true
            #    spec:
            #      httpGet:
            #        port: 6060
            #        path: /api/v1/health/check
            #  readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 12m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      rmqtt:
        controller: rmqtt
        type: ClusterIP
        clusterIP: None
        publishNotReadyAddresses: true
        ports:
          grpc:
            port: 5363
          raft:
            port: 6003
      mqtt:
        controller: rmqtt
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: mqtt.jonandlinz.io
          gatus.home-operations.com/endpoint: |-
            group: services
          lbipam.cilium.io/ips: 10.12.0.105
        externalTrafficPolicy: Local
        ports:
          mqtt:
            port: 1883
          http:
            port: 6060
    serviceMonitor:
      rmqtt:
        serviceName: rmqtt-mqtt
        endpoints:
          - port: http
            scheme: http
            path: /api/v1/metrics/prometheus
    configMaps:
      config:
        data:
          rmqtt-retainer.toml: |
            storage.type = "redis"
            storage.redis.url = "redis://dragonfly.database.svc.cluster.local:6379/6"
            storage.redis.prefix = "retain"
            retained_message_ttl = "0m"
          rmqtt.toml: |
            log.to = "console"
            log.level = "info"
            plugins.dir = "rmqtt-plugins/"
    persistence:
      user-acl:
        type: secret
        name: rmqtt-secret
        globalMounts:
          - path: /app/rmqtt/rmqtt-plugins/rmqtt-acl.toml
            subPath: rmqtt-acl.toml
            readOnly: true
      plugins:
        type: configMap
        name: rmqtt
        globalMounts:
          - path: /app/rmqtt/rmqtt.toml
            subPath: rmqtt.toml
          - path: /app/rmqtt/rmqtt-plugins/rmqtt-retainer.toml
            subPath: rmqtt-retainer.toml